In [9]:
raw_data_dir = "/media/nampv1/hdd/data/vnpost-asr/CommonVoice22Vi/raw/cv-corpus-22.0-2025-06-20/vi"

In [2]:
import os

In [10]:
os.listdir(raw_data_dir)

['clips',
 'clip_durations.tsv',
 'dev.tsv',
 'invalidated.tsv',
 'other.tsv',
 'reported.tsv',
 'test.tsv',
 'train.tsv',
 'unvalidated_sentences.tsv',
 'validated.tsv',
 'validated_sentences.tsv']

In [11]:
len(os.listdir(os.path.join(raw_data_dir, "clips")))

18761

In [12]:
import pandas as pd

In [15]:
pd.read_csv(os.path.join(raw_data_dir, "clip_durations.tsv"), sep="\t")

                               clip  duration[ms]
0      common_voice_vi_25226546.mp3          2196
1      common_voice_vi_30579154.mp3          4248
2      common_voice_vi_24124535.mp3          4716
3      common_voice_vi_24552157.mp3          4176
4      common_voice_vi_24523018.mp3          5256
...                             ...           ...
18756  common_voice_vi_24535282.mp3          4608
18757  common_voice_vi_26227221.mp3          2376
18758  common_voice_vi_25273399.mp3          3636
18759  common_voice_vi_25268008.mp3          4536
18760  common_voice_vi_25223919.mp3          3636

[18761 rows x 2 columns]

In [21]:
total = 0

tsv_files = [os.path.join(raw_data_dir, fn) for fn in os.listdir(raw_data_dir) if fn.endswith(".tsv")]

for file in tsv_files:
    print(os.path.basename(file))

    df = pd.read_csv(os.path.join(raw_data_dir, file), sep="\t")
    total += len(df)
    print(len(df))

print(total)

clip_durations.tsv
18761
dev.tsv
931
invalidated.tsv
433
other.tsv
11516
reported.tsv
199
test.tsv
1014
train.tsv
2104
unvalidated_sentences.tsv
5464
validated.tsv
5391
validated_sentences.tsv
6275
52088

In [24]:
df_dev = pd.read_csv(os.path.join(raw_data_dir, "dev.tsv"), sep="\t")
df_dev

,client_id,path,sentence_id,sentence,sentence_domain,up_votes,down_votes,age,gender,accents,variant,locale,segment
0,b5a488f63805ea511df396c46afe3819f6ee9f3dbdf3be...,common_voice_vi_25225608.mp3,b328dc0be3e3521cae9bf8b2ecd9a0e94aef4b75ab9f92...,Ngày nào đó trên mặt trang kỷ niệm,NaN,2,1,twenties,male_masculine,NaN,NaN,vi,NaN
1,b5a488f63805ea511df396c46afe3819f6ee9f3dbdf3be...,common_voice_vi_25225610.mp3,c77b3a95feccc2ad00e5d294390f2b9866c38155047fe0...,vậy phải làm thế nào,NaN,2,0,twenties,male_masculine,NaN,NaN,vi,NaN
2,b5a488f63805ea511df396c46afe3819f6ee9f3dbdf3be...,common_voice_vi_25225618.mp3,b5353074a3372ccdca28b425c35ab238514c63a71b6fa5...,Còn hai người nữa sẽ ở chung với A Hội,NaN,2,0,twenties,male_masculine,NaN,NaN,vi,NaN
3,b5a488f63805ea511df396c46afe3819f6ee9f3dbdf3be...,common_voice_vi_25225635.mp3,bb8512c2a6a0acc4cb01a44ded2416d7d0ede2e2bbdc3d...,"Bực thế chứ, xe để đây sao lại xịt lốp được",NaN,2,1,twenties,male_masculine,NaN,NaN,vi,NaN
4,b5a488f63805ea511df396c46afe3819f6ee9f3dbdf3be...,common_voice_vi_25225644.mp3,bc7c053ca0e78f1df013123e89f540b89acb960ee395f5...,suốt ngày đem hòn đá đó bên người con cũng thấ...,NaN,2,0,twenties,male_masculine,NaN,NaN,vi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,c29d07b14c1806169f49b175b3bc29a620bd2d4c2291a4...,common_voice_vi_25275953.mp3,d8363977a94ac05ce998288bdb48fd072e5fec4e4c2f6d...,hình ảnh của ông được nhiều người dân,NaN,2,0,teens,female_feminine,NaN,NaN,vi,NaN
927,c29d07b14c1806169f49b175b3bc29a620bd2d4c2291a4...,common_voice_vi_25275988.mp3,c5276511ae83fbe0051720db8401b8073b4e8ab09d94a3...,em liền gào lên,NaN,2,0,teens,female_feminine,NaN,NaN,vi,NaN
928,c29d07b14c1806169f49b175b3bc29a620bd2d4c2291a4...,common_voice_vi_25276351.mp3,d843a9a10ad1dd4670a4ec47a100e289323d7290bb432f...,Chắc những chuyện ma quái anh cũng từng trải,NaN,2,0,teens,female_feminine,NaN,NaN,vi,NaN
929,c29d07b14c1806169f49b175b3bc29a620bd2d4c2291a4...,common_voice_vi_25276390.mp3,cfd7c7b2526d5c5d4dc312919c3a7931ba1f382b543844...,treo trong nhà,NaN,2,0,teens,female_feminine,NaN,NaN,vi,NaN
930,c29d07b14c1806169f49b175b3bc29a620bd2d4c2291a4...,common_voice_vi_25276414.mp3,e2bc08ab464748489a49c280deceb259e4afcccdbfb689...,Càng ngày chinh lại càng Đặt Niềm Tin tuyệt đố...,NaN,2,0,teens,female_feminine,NaN,NaN,vi,NaN